#Environment URL
url = xxxxx

#Environment Credentials
username = xxxx
password = xxxxx

#External File Paths
driverPath = ./chromedriver.exe
driverKey = webdriver.chrome.driver
excelFilePath = ./Test Execution Script.xlsx
excelSheetName = Test Data
resultSheetName = Result Sheet
reportsFilePath = ./ExtentReports.html
reportsConfigFile = ./src/extent-config.xml