#Environment URL
url = http://182.72.164.246:91/oiexc/CASMEX/Login.aspx

#Environment Credentials
username = CASMEX
password = Test@12345

#External File Paths
driverPath = ./chromedriver.exe
driverKey = webdriver.chrome.driver
excelFilePath = ./Test Execution Script.xlsx
excelSheetName = Test Data
resultSheetName = Result Sheet
reportsFilePath = ./ExtentReports.html
reportsConfigFile = extent-config.xml